server_ip =  "192.168.56.110"

server_script = <<-SHELL

  set -e
  apt-get update && apt-get install -y curl vim

  # Install Docker
  curl -fsSL https://get.docker.com -o get-docker.sh
  sh get-docker.sh

  # Install K3d
  curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

  # Create a cluster and expose ports 8081 and 8082
  k3d cluster create dev-cluster --api-port 6550 --port 8081:80@loadbalancer --port 8082:443@loadbalancer

  # create k3d kubeconfig file
  cp $(k3d kubeconfig write dev-cluster) /vagrant_shared/kubeconfig

  # Install kubectl
  curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  install -o vagrant -g vagrant -m 0755 kubectl /usr/local/bin/kubectl

  # Install Helm
  curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
  chmod 700 get_helm.sh
  ./get_helm.sh

  # Install k9s
  wget https://github.com/derailed/k9s/releases/download/v0.32.7/k9s_linux_amd64.deb && apt install ./k9s_linux_amd64.deb && rm k9s_linux_amd64.deb

SHELL

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "srachdiS" do |c|
    c.vm.hostname = "srachdiS"
    c.vm.network "private_network", ip: server_ip
    c.vm.synced_folder "./shared", "/vagrant_shared"
    c.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "srachdiS","--cpus", 4, "--memory", 2048]
    end
    c.vm.provision "shell", inline: server_script
  end
end
